/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Dashboard;

/**
 *
 * @author sruja
 */
public class ThirdPanelDashboard extends javax.swing.JPanel {

    /**
     * Creates new form ThirdPanelDashboard
     */
    private ArrayList<String> week = new ArrayList<String>();
    DataReader commentReader;
    Map<String, String> weekValues = new HashMap<>();
    
    public thirdPanelDashboard() {
        initComponents();
                
        for(int i = 0;i < 40; i++){
            week.add("Week"+(i+1));
        }
        populateDropdown();
        readCSV();
    }
    private void readCSV(){
        try {
            commentReader = new DataReader("C:\\Northeastern\\Assignments\\AED_Final_Proj_Adoption_System\\ChildAdoptionSystem\\src\\Document\\PregnancyProgress.csv");
            try {
                readData();
            } catch (IOException ex) {
                Logger.getLogger(BirthMotherDashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
            catch (FileNotFoundException ex) {
            Logger.getLogger(BirthMotherDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    private void readData() throws IOException{
        String[] row;
        while((row = commentReader.getNextRow()) != null ){            
            generate(row);
            System.out.println("");
        }
    }
    
    private void generate(String[] row){
        // TODO
        String week = row[0];
        String detail = row[1];
        
        weekValues.put(week, detail);
                
       // System.out.print(week);
       // System.out.print(detail);
    }
    
    private void populateDropdown(){
    
        selectWeekComboBox.removeAllItems();
        selectWeekComboBox.addItem("Select week");
        
        for(String week: week){
           selectWeekComboBox.addItem(week);
        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLearn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaInstructions = new javax.swing.JTextArea();
        imgBaby = new javax.swing.JLabel();
        selectWeekComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        btnLearn.setText("Learn");
        btnLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLearnActionPerformed(evt);
            }
        });

        txtAreaInstructions.setColumns(20);
        txtAreaInstructions.setRows(5);
        txtAreaInstructions.setText("Avoid alcohol, drugs, and tobacco products.\nTalk to your doctor about any prescription and \nnonprescription (OTC) drugs you are taking. aintain a \ndiet that contains an \nadequate amount of vitamins, especially folic acid.");
        jScrollPane1.setViewportView(txtAreaInstructions);

        selectWeekComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectWeekComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectWeekComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("Selected week:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectWeekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imgBaby))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLearn)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(selectWeekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLearn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imgBaby, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addContainerGap(324, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearnActionPerformed
        // TODO add your handling code here:
        String selection = selectWeekComboBox.getSelectedItem().toString();

        if(weekValues.containsKey(selection)){
            txtAreaInstructions.setText(weekValues.get(selection));
        }

        URL urlToImage = this.getClass().getResource("/Images/"+selection+".png");
        imgBaby.setIcon(new ImageIcon(urlToImage));
    }//GEN-LAST:event_btnLearnActionPerformed

    private void selectWeekComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectWeekComboBoxActionPerformed

    }//GEN-LAST:event_selectWeekComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLearn;
    private javax.swing.JLabel imgBaby;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selectWeekComboBox;
    private javax.swing.JTextArea txtAreaInstructions;
    // End of variables declaration//GEN-END:variables
}
